import type { FiscalRule } from './rules';

const PROVENANCE_2026 = {
  jurisdiction: 'RO',
  entityType: 'PFA',
  taxYear: 2026,
  verifiedAt: '2026-01-01',
  status: 'ACTIVE' as const,
  version: 1,
};

export const PFA_2026_SYSTEM_REAL_PACKAGE: FiscalRule[] = [
  {
    ...PROVENANCE_2026,
    ruleId: 'PFA_2026_TAX_REFERENCE',
    name: 'PFA 2026 tax reference (4050 lei)',
    taxRegime: 'wage-reference',
    effectiveFrom: '2026-01-01',
    effectiveTo: null,
    parameters: [
      { id: 'reference', label: 'Reference value', value: 4050, unit: 'lei' },
      { id: 'multiple_6x', label: '6x reference', value: 24300, unit: 'lei' },
      { id: 'multiple_12x', label: '12x reference', value: 48600, unit: 'lei' },
      { id: 'multiple_24x', label: '24x reference', value: 97200, unit: 'lei' },
      { id: 'multiple_72x', label: '72x reference', value: 291600, unit: 'lei' },
    ],
    calculatorId: 'calc-wage-reference',
    sourceAct: 'HG 1506/2024',
    sourceArticle: 'art. 1',
    sourceUrl: 'https://www.legalteka.ro/act/1506/2024',
  },
  {
    ...PROVENANCE_2026,
    ruleId: 'GENERAL_MINIMUM_WAGE_2026_H1',
    name: 'Minimum wage H1 2026 (Jan–Jun)',
    taxRegime: 'wage-reference',
    effectiveFrom: '2026-01-01',
    effectiveTo: '2026-06-30',
    parameters: [
      { id: 'monthly', label: 'Monthly minimum wage', value: 4050, unit: 'lei' },
    ],
    calculatorId: 'calc-wage-reference',
    sourceAct: 'HG 1506/2024',
    sourceArticle: 'art. 1',
    sourceUrl: 'https://www.legalteka.ro/act/1506/2024',
  },
  {
    ...PROVENANCE_2026,
    ruleId: 'GENERAL_MINIMUM_WAGE_2026_H2',
    name: 'Minimum wage H2 2026 (Jul–Dec)',
    taxRegime: 'wage-reference',
    effectiveFrom: '2026-07-01',
    effectiveTo: null,
    parameters: [
      { id: 'monthly', label: 'Monthly minimum wage', value: 4325, unit: 'lei' },
    ],
    calculatorId: 'calc-wage-reference',
    sourceAct: 'HG 146/2026',
    sourceArticle: 'art. 1',
    sourceUrl: 'https://www.legalteka.ro/act/146/2026',
  },
  {
    ...PROVENANCE_2026,
    ruleId: 'CAS_2026',
    name: 'CAS 2026 (25%)',
    taxRegime: 'cas',
    effectiveFrom: '2026-01-01',
    effectiveTo: null,
    parameters: [
      { id: 'rate', label: 'CAS rate', value: 25, unit: 'percent' },
      { id: 'min_base', label: 'Minimum base (12 SM annual)', value: 48600, unit: 'lei' },
      { id: 'max_base', label: 'Maximum base (24 SM annual)', value: 97200, unit: 'lei' },
      { id: 'min_cas', label: 'Minimum CAS', value: 12150, unit: 'lei' },
      { id: 'max_cas', label: 'Maximum CAS', value: 24300, unit: 'lei' },
    ],
    calculatorId: 'calc-cas',
    sourceAct: 'ANAF 2026',
    sourceArticle: 'CAS 2026',
    sourceUrl: 'https://www.anaf.ro',
  },
  {
    ...PROVENANCE_2026,
    ruleId: 'CASS_2026',
    name: 'CASS 2026 (10%)',
    taxRegime: 'cass',
    effectiveFrom: '2026-01-01',
    effectiveTo: null,
    parameters: [
      { id: 'rate', label: 'CASS rate', value: 10, unit: 'percent' },
      { id: 'min_base', label: 'Minimum base (6 SM annual)', value: 24300, unit: 'lei' },
      { id: 'max_annual_base', label: 'Max annual base (72 SM)', value: 291600, unit: 'lei' },
      { id: 'min_cass', label: 'Minimum CASS', value: 2430, unit: 'lei' },
      { id: 'max_cass', label: 'Maximum CASS', value: 29160, unit: 'lei' },
    ],
    calculatorId: 'calc-cass',
    sourceAct: 'ANAF 2026',
    sourceArticle: 'CASS 2026',
    sourceUrl: 'https://www.anaf.ro',
  },
  {
    ...PROVENANCE_2026,
    ruleId: 'INCOME_TAX_2026',
    name: 'Income tax 2026 (10% + 16%)',
    taxRegime: 'income-tax',
    effectiveFrom: '2026-01-01',
    effectiveTo: null,
    parameters: [
      { id: 'base_rate', label: 'Base rate', value: 10, unit: 'percent' },
      { id: 'progressive_rate', label: 'Progressive rate', value: 16, unit: 'percent' },
    ],
    calculatorId: 'calc-income-tax',
    sourceAct: 'ANAF 2026',
    sourceArticle: 'Income tax 2026',
    sourceUrl: 'https://www.anaf.ro',
  },
  {
    ...PROVENANCE_2026,
    ruleId: 'VAT_THRESHOLD_2026',
    name: 'VAT registration threshold 2026',
    taxRegime: 'vat',
    effectiveFrom: '2025-09-01',
    effectiveTo: null,
    parameters: [
      { id: 'threshold', label: 'VAT threshold', value: 395000, unit: 'lei' },
    ],
    calculatorId: 'calc-vat-threshold',
    sourceAct: 'ANAF 2026',
    sourceArticle: 'art. 338 Cod. fisc.',
    sourceUrl: 'https://www.anaf.ro',
  },
  {
    ...PROVENANCE_2026,
    ruleId: 'PFA_DEADLINE_2026',
    name: 'PFA single deadline 2026',
    taxRegime: 'deadlines',
    effectiveFrom: '2026-01-01',
    effectiveTo: null,
    parameters: [
      { id: 'deadline', label: 'Single deadline', value: '2027-05-25', unit: 'date' },
    ],
    calculatorId: 'calc-deadline',
    sourceAct: 'ANAF 2026',
    sourceArticle: 'Deadlines 2026',
    sourceUrl: 'https://www.anaf.ro',
  },
];
